---
- hosts: myhosts
  connection: local
  name: Get boot order
  gather_facts: False

  vars:
    datatype: BootOrder

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get device boot order
    redfish_info:
      category: Systems
      command: GetBootOrder
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
