---
- hosts: myhosts
  connection: local
  name: Manage System Power - Reboot
  gather_facts: False

  tasks:

  - name: Reboot system power
    redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
