---
- hosts: myhosts
  connection: local
  name: Set one-time BIOS boot device (UEFI target mode)
  gather_facts: False

  vars:
    - bootdevice: UefiTarget
    - uefi_target: "/0x31/0x33/0x01/0x01"

  tasks:

  - name: Set one-time boot device to {{ bootdevice }}
    redfish_command:
      category: Systems
      command: SetOneTimeBoot
      bootdevice: "{{ bootdevice }}"
      uefi_target: "{{ uefi_target }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: onetimeboot

  - name: Reboot system
    redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: onetimeboot.changed
