---
- hosts: myhosts
  connection: local
  name: Set one-time boot device (UEFI boot next mode)
  gather_facts: False

  vars:
    - bootdevice: UefiBootNext
    - boot_next: Boot0001

  tasks:

  - name: Set one-time boot device to {{ bootdevice }}
    redfish_command:
      category: Systems
      command: SetOneTimeBoot
      bootdevice: "{{ bootdevice }}"
      boot_next: "{{ boot_next }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: onetimeboot

  - name: Reboot system
    redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: onetimeboot.changed
