---
- hosts: myhosts
  connection: local
  name: Set one-time boot device (legacy mode)
  gather_facts: False

  # Bootdevice options include: None, Pxe, Cd, Floppy, Hdd, BiosSetup,
  # Usb, Utilities, Diags, UefiShell, and SDCard.

  vars:
    - bootdevice: Pxe

  tasks:

  - name: Set one-time boot device to {{ bootdevice }}
    redfish_command:
      category: Systems
      command: SetOneTimeBoot
      bootdevice: "{{ bootdevice }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: onetimeboot

  - name: Reboot system
    redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: onetimeboot.changed
