---
- hosts: myhosts
  connection: local
  name: Clear System Logs
  gather_facts: False

  tasks:

  - name: Clear Logs
    redfish_command:
      category: Manager
      command: ClearLogs
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
