---
- hosts: myhosts
  connection: local
  name: Get Manager Logs
  gather_facts: False

  vars:
    datatype: Logs

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get Manager Logs
    redfish_facts:
      category: Manager
      command: GetLogs
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
