---
- hosts: myhosts
  connection: local
  name: Get Manager NIC inventory
  gather_facts: False

  vars:
    datatype: ManagerNicInventory

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get Manager NIC inventory
    redfish_facts:
      category: Manager
      command: GetManagerNicInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
