---
- hosts: myhosts
  connection: local
  name: Restart Manager
  gather_facts: False

  tasks:

  - name: Restart Manager gracefully
    redfish_command:
      category: Manager
      command: GracefulRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
