---
- hosts: myhosts
  connection: local
  name: Chassis Health Report
  gather_facts: False

  vars:
    datatype: ChassisHealth

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Getting chassis health report
    redfish_info:
      category: Chassis
      command: GetHealthReport
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
