---
- hosts: myhosts
  connection: local
  name: Set Indicator LED to On
  gather_facts: False

  tasks:

  - name: Turn LED on
    redfish_command:
      category: Chassis
      command: IndicatorLedOn
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
