---
- hosts: myhosts
  connection: local
  name: Set Indicator LED to Off
  gather_facts: False

  tasks:

  - name: Turn LED off
    redfish_command:
      category: Chassis
      command: IndicatorLedOff
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
