---
- hosts: myhosts
  connection: local
  name: Set Indicator LED to Blink
  gather_facts: False

  tasks:

  - name: Blink LED
    redfish_command:
      category: Chassis
      command: IndicatorLedBlink
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
